# The Xcode project is not standalone: we need the Cocoapods-generated workspace to draw dependencies.
xcodebuild_arguments:
    - -workspace
    - InstantSearchCore.xcworkspace
    - -scheme
    - InstantSearchCore-iOS
output: build/doc
# Avoid putting the DocSet within the HTML docs.
# WARNING: The path is relative to the output directory.
docset_path: ../docset
hide_documentation_coverage: true
abstract:
    - LICENSE
custom_categories:
    - name: Searching
      children:
        - Searcher
        - SearchParameters
        - FacetRefinement
        - NumericRefinement
        - SearchResults
        - HighlightResult
        - SnippetResult
        - RankingInfo
        - FacetStats
        - FacetValue

    - name: Utilities
      children:
        - Highlighter
        - Debouncer
        - SearchProgressController
