# The Xcode project is not standalone: we need the Cocoapods-generated workspace to draw dependencies.
xcodebuild_arguments:
    - -workspace
    - AlgoliaSearchHelper.xcworkspace
    - -scheme
    - AlgoliaSearchHelper-iOS
output: build/doc
# Avoid putting the DocSet within the HTML docs.
# WARNING: The path is relative to the output directory.
docset_path: ../docset
hide_documentation_coverage: true
