branches:
    only:
        - master
osx_image: xcode9
language: objective-c
env:
    matrix:
         - PLATFORM="OSX"    SDK="macosx10.13"
         - PLATFORM="iOS"    SDK="iphonesimulator11.0"    DESTINATION="OS=11.0,name=iPhone 6"
         - PLATFORM="tvOS"   SDK="appletvsimulator11.0"   DESTINATION="OS=11.0,name=Apple TV 1080p"
before_install:
    - brew update
    - brew upgrade carthage 

install:
    - travis_wait 30 carthage update
before_script:
    - gem install xcpretty -N
script:
    - set -o pipefail
    - travis_retry xcodebuild -workspace InstantSearchCore.xcworkspace -scheme "InstantSearchCore-${PLATFORM}" -sdk "${SDK}" -destination "${DESTINATION}" test
