branches:
    only:
        - master
osx_image: xcode8
language: objective-c
env:
    matrix:
        - PLATFORM="macOS"  SDK="macosx10.12"            DESTINATION="platform=macOS"
        - PLATFORM="iOS"    SDK="iphonesimulator10.0"    DESTINATION="OS=10.0,name=iPhone 6"
        - PLATFORM="tvOS"   SDK="appletvsimulator10.0"   DESTINATION="OS=10.0,name=Apple TV 1080p"
install:
    - pod install --repo-update
before_script:
    - gem install xcpretty -N
script:
    - set -o pipefail
    - travis_retry xcodebuild -workspace InstantSearchCore.xcworkspace -scheme "InstantSearchCore-${PLATFORM}" -sdk "${SDK}" -destination "${DESTINATION}" test
